In [1]:
import pandas as pd
# csv_path= '/home/ubuntu/Documents/Nafisha/GenSeg-VS/GenSeg_VS.csv'
csv_path = '/home/ubuntu/Documents/Nafisha/GenSeg-VS/GenSeg_VS_omen.csv'
df= pd.read_csv(csv_path)
df.columns

Index(['patient_id', 'y_value', 'image_path', 'SegmentationPath',
       'image_nifti', 'mask_nifti'],
      dtype='object')

In [2]:
df = df.drop(columns=['image_path', 'SegmentationPath'])
df

,patient_id,y_value,image_nifti,mask_nifti
0,VS-MC-RC-001,0,/home/omen/Documents/Nafisha/VS_data_nifti_Gen...,/home/omen/Documents/Nafisha/VS_data_nifti_Gen...
1,VS-MC-RC-002,1,/home/omen/Documents/Nafisha/VS_data_nifti_Gen...,/home/omen/Documents/Nafisha/VS_data_nifti_Gen...
2,VS-MC-RC-004,0,/home/omen/Documents/Nafisha/VS_data_nifti_Gen...,/home/omen/Documents/Nafisha/VS_data_nifti_Gen...
3,VS-MC-RC-005,1,/home/omen/Documents/Nafisha/VS_data_nifti_Gen...,/home/omen/Documents/Nafisha/VS_data_nifti_Gen...
4,VS-MC-RC-006,1,/home/omen/Documents/Nafisha/VS_data_nifti_Gen...,/home/omen/Documents/Nafisha/VS_data_nifti_Gen...
...,...,...,...,...
97,VS-SEG-188,1,/home/omen/Documents/Nafisha/VS_data_nifti_Gen...,/home/omen/Documents/Nafisha/VS_data_nifti_Gen...
98,VS-SEG-197,1,/home/omen/Documents/Nafisha/VS_data_nifti_Gen...,/home/omen/Documents/Nafisha/VS_data_nifti_Gen...
99,VS-SEG-199,1,/home/omen/Documents/Nafisha/VS_data_nifti_Gen...,/home/omen/Documents/Nafisha/VS_data_nifti_Gen...
100,VS-SEG-218,1,/home/omen/Documents/Nafisha/VS_data_nifti_Gen...,/home/omen/Documents/Nafisha/VS_data_nifti_Gen...
101,VS-SEG-221,1,/home/omen/Documents/Nafisha/VS_data_nifti_Gen...,/home/omen/Documents/Nafisha/VS_data_nifti_Gen...

In [6]:
for idx, row in df.iterrows():
    image_path= row['image_nifti']
    mask_path= row['mask_nifti']
    df.loc[idx, 'image_nifti']= image_path.replace('omen', 'ubuntu')
    df.loc[idx, 'mask_nifti']= mask_path.replace('omen', 'ubuntu')
    # print(df['image_nifti'])
    # break

In [7]:
df

,patient_id,y_value,image_nifti,mask_nifti
0,VS-MC-RC-001,0,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...
1,VS-MC-RC-002,1,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...
2,VS-MC-RC-004,0,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...
3,VS-MC-RC-005,1,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...
4,VS-MC-RC-006,1,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...
...,...,...,...,...
97,VS-SEG-188,1,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...
98,VS-SEG-197,1,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...
99,VS-SEG-199,1,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...
100,VS-SEG-218,1,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...
101,VS-SEG-221,1,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...

In [5]:
# for idx, row in df.iterrows():
#     df.loc[idx, 'image_nifti'] = f'/home/ubuntu/Documents/Nafisha/VS_data_nifti_Genseg/Image/image{idx+1}'
#     df.loc[idx, 'mask_nifti'] = f'/home/ubuntu/Documents/Nafisha/VS_data_nifti_Genseg/Mask/mask{idx+1}'

In [10]:
# n=102
# df = pd.DataFrame({
#     "image_nifti": [f"/home/ubuntu/Documents/Nafisha/VS_data_nifti_Genseg/Image/image{i+1}.nii.gz" for i in range(n)],
#     "mask_nifti":  [f"/home/ubuntu/Documents/Nafisha/VS_data_nifti_Genseg/Mask/mask{i+1}.nii.gz" for i in range(n)]
# })

In [10]:
output_path = "/home/ubuntu/Documents/Nafisha/GenSeg-VS/GenSeg_VS.csv"
df.to_csv(output_path, index=False)

In [8]:
import os
for idx, row in df.iterrows():
    if not os.path.exists(row['image_nifti']):
        print(row['image_nifti'])

    if not os.path.exists(row['mask_nifti']):
        print(row['mask_nifti'])

In [9]:
df

,patient_id,y_value,image_nifti,mask_nifti
0,VS-MC-RC-001,0,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...
1,VS-MC-RC-002,1,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...
2,VS-MC-RC-004,0,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...
3,VS-MC-RC-005,1,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...
4,VS-MC-RC-006,1,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...
...,...,...,...,...
97,VS-SEG-188,1,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...
98,VS-SEG-197,1,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...
99,VS-SEG-199,1,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...
100,VS-SEG-218,1,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...
101,VS-SEG-221,1,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...,/home/ubuntu/Documents/Nafisha/VS_data_nifti_G...